# This is the configuration used to check the rubocop source code.
---

# inherit_from: .rubocop_todo.yml

AllCops:
#   Exclude:
#     - "spec/fixtures/**/*"
#     - "tmp/**/*"
#     - "vendor/**/*"
#     - "node_modules/**/*"
  TargetRubyVersion: 2.6

Bundler/OrderedGems:
  Enabled: false


Layout/AlignHash:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2] # min: 1, max: 2

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true
  # ForceEqualSignAlignment: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false


Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousOperator:
  Enabled: false


Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  # crystal <3
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  # crystal <3
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - "db/**/*"

Style/AndOr:
  EnforcedStyle: conditionals

# Style/AsciiComments:
#   Enabled: false

Style/CommentedKeyword:
  Exclude:
    - "spec/**/*.rb"



# Style/DoubleNegation:
#   Enabled: false

# Style/Encoding:
#   Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# Style/ModuleFunction:
#   Enabled: false # there area differences between `module_function` and `extend self` (e.g. private methods)

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false


# Layout/IndentArray:
#   EnforcedStyle: consistent

# Layout/IndentHeredoc:
#   EnforcedStyle: powerpack

# Layout/MultilineMethodCallIndentation:
#   EnforcedStyle: indented

# Lint/AmbiguousBlockAssociation:
#   Exclude:
#     - "spec/**/*.rb"

# Lint/UselessAccessModifier:
#   MethodCreatingMethods:
#     - "def_matcher"
#     - "def_node_matcher"

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 14

Metrics/LineLength:
  Max: 110

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"
